<a href="https://colab.research.google.com/github/DeussTenebris/Dissertation_GibranAndrade/blob/main/Loan_Eligibility_Top_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as ptl

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:

#pathfinder from dataset
dataset_path = '/content/drive/MyDrive/Datasets/Dissertation/Test Eligibility DB.xlsx' #Dataset containing 300 records from QUALTRICS

dataset_path_surveys = '/content/drive/MyDrive/Datasets/Dissertation/Qualtrics Dataset.xlsx' #Dataset adding 103 new records from QUALTIRICS

dataset = pd.read_excel(dataset_path) #setting pathfinder

In [ ]:

#dataset discovery
dataset.info()
dataset.shape
dataset.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   TempId                      300 non-null    int64  
 1   Age                         300 non-null    int64  
 2   Working Age                 300 non-null    float64
 3   Credit Score                300 non-null    int64  
 4   Income                      300 non-null    float64
 5   Client Payment              300 non-null    int64  
 6   House Price (Casa Popular)  300 non-null    float64
 7   Profesionist                300 non-null    int64  
 8   Residence                   300 non-null    int64  
 9   Employment Type             300 non-null    int64  
 10  Dependents                  300 non-null    int64  
 11  prediction                  300 non-null    int64  
dtypes: float64(3), int64(9)
memory usage: 28.2 KB


TempId                        0
Age                           0
Working Age                   0
Credit Score                  0
Income                        0
Client Payment                0
House Price (Casa Popular)    0
Profesionist                  0
Residence                     0
Employment Type               0
Dependents                    0
prediction                    0
dtype: int64

In [ ]:
dataset.head()

TempId  Age  Working Age  Credit Score    Income  Client Payment  \
0      99   50         7.70           377  334856.4              50   
1      98   33         3.80           674  654732.3              75   
2      97   32         3.25           573  435208.5              53   
3      96   64        11.70           277  585687.3              72   
4      95   64         2.40           376  823562.4              19   

   House Price (Casa Popular)  Profesionist  Residence  Employment Type  \
0                   2173766.9             1          0                2   
1                    982253.7             1          0                1   
2                    757977.1             1          1                0   
3                   1017826.0             0          1                2   
4                   1651254.3             0          0                0   

   Dependents  prediction  
0           1           0  
1           1           0  
2           1           6  
3           1           0  
4           0           0

In [ ]:

# Define features and target variable
X = dataset.drop(['prediction', 'TempId'], axis=1)  # Drop TempId as it is not a feature
y = dataset['prediction']
X.head()


Age  Working Age  Credit Score    Income  Client Payment  \
0   50         7.70           377  334856.4              50   
1   33         3.80           674  654732.3              75   
2   32         3.25           573  435208.5              53   
3   64        11.70           277  585687.3              72   
4   64         2.40           376  823562.4              19   

   House Price (Casa Popular)  Profesionist  Residence  Employment Type  \
0                   2173766.9             1          0                2   
1                    982253.7             1          0                1   
2                    757977.1             1          1                0   
3                   1017826.0             0          1                2   
4                   1651254.3             0          0                0   

   Dependents  
0           1  
1           1  
2           1  
3           1  
4           0

In [ ]:
# Z-score normalization
from sklearn.preprocessing import StandardScaler
def normalization (X,y):
    scaler = StandardScaler()
    X_scaled = 0
    X_scaled = scaler.fit_transform(X)

    # Convert the scaled data in x back to a DataFrame
    X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

    # Display the first few rows of the scaled DataFrame
    print("Z-Scored Variables (X): ", + X_scaled_df.head())
    print(X_scaled_df.shape)

    print("\n Target Variable (y):\n", + y.head())
    # Check unique values in the target variable
    unique_classes = y.unique()
    print(f'Unique classes in the target variable: {unique_classes}')
    return X_scaled_df, y


In [ ]:
#Callling current dataset
X, y = normalization(X, y)

Z-Scored Variables (X):          Age  Working Age  Credit Score    Income  Client Payment  \
0 -0.009815     0.060512     -0.601586 -0.839459        0.167384   
1 -0.887956    -0.692670      1.430768  0.552290        1.387388   
2 -0.939611    -0.798888      0.739631 -0.402837        0.313785   
3  0.713360     0.833006     -1.285880  0.251882        1.240987   
4  0.713360    -0.963043     -0.608429  1.286853       -1.345420   

   House Price (Casa Popular)  Profesionist  Residence  Employment Type  \
0                    1.478968      0.993355  -1.135815         1.263353   
1                   -0.053686      0.993355  -1.135815         0.028806   
2                   -0.342176      0.993355   0.880425        -1.205741   
3                   -0.007929     -1.006689   0.880425         1.263353   
4                    0.806855     -1.006689  -1.135815        -1.205741   

   Dependents  
0    1.047808  
1    1.047808  
2    1.047808  
3    1.047808  
4   -0.954373  
(300, 10)

 Target 

In [ ]:
X.head()

Age  Working Age  Credit Score    Income  Client Payment  \
0 -0.009815     0.060512     -0.601586 -0.839459        0.167384   
1 -0.887956    -0.692670      1.430768  0.552290        1.387388   
2 -0.939611    -0.798888      0.739631 -0.402837        0.313785   
3  0.713360     0.833006     -1.285880  0.251882        1.240987   
4  0.713360    -0.963043     -0.608429  1.286853       -1.345420   

   House Price (Casa Popular)  Profesionist  Residence  Employment Type  \
0                    1.478968      0.993355  -1.135815         1.263353   
1                   -0.053686      0.993355  -1.135815         0.028806   
2                   -0.342176      0.993355   0.880425        -1.205741   
3                   -0.007929     -1.006689   0.880425         1.263353   
4                    0.806855     -1.006689  -1.135815        -1.205741   

   Dependents  
0    1.047808  
1    1.047808  
2    1.047808  
3    1.047808  
4   -0.954373

In [ ]:
#Method to find top to predictions
def get_top_two_classes(proba):
    top_two = np.argsort(proba, axis=1)[:, -2:][:, ::-1]
    return top_two

In [ ]:

#Split data into training and testing
from sklearn.model_selection import train_test_split # library

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20) # Specifies the test dataset as 20% of the data, the 80% rest is located to the training

#Ensuring correct data size
print('x_train: ', X_train.shape)
print('y_train: ',y_train.shape)
print('x_test: ', X_test.shape)
print('y_test: ', y_test.shape)

x_train:  (240, 10)
y_train:  (240,)
x_test:  (60, 10)
y_test:  (60,)


**Model Selection**

In [ ]:
# importing reporting
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
###Logistic Regression

#importing library from sklearn
from sklearn.linear_model import LogisticRegression
def logistic_reg (X_test, y_test, X_train, y_train):

    # Initialize and train the Logistic Regression model
    log_reg = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000, random_state=42)
    log_reg.fit(X_train, y_train)

    # Predict probabilities on the test set
    y_proba_lr = log_reg.predict_proba(X_test)

    # Method to find top two predictions
    def get_top_two_classes(proba):
        top_two = np.argsort(proba, axis=1)[:, -2:][:, ::-1]
        return top_two

    # Get top two predictions
    top_two_predictions_lr = get_top_two_classes(y_proba_lr)

    # Predict probabilities on the test set
    y_proba_lr = log_reg.predict_proba(X_test)

    # Get top two predictions
    top_two_predictions_lr = get_top_two_classes(y_proba_lr)


    print("Logistic Regression Top Two Predictions:")
    for i in range(len(X_test)):
        print(f"Test instance {i}:")
        top_two = top_two_predictions_lr[i]
        if top_two[0] == -1:  # Both classes are marked
            print(f"Top two predicted classes: {top_two}")
            print(f"Probabilities: {y_proba_lr[i][top_two]}")
        else:
            print(f"Top predicted class: {top_two[0]}")
            print(f"Probability: {y_proba_lr[i][top_two[0]]}")
        print()

    # Predict on the test set
    y_pred_lr = log_reg.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred_lr)
    print(f"Accuracy: {accuracy:.2f}")

    # Print classification report
    print(classification_report(y_test, y_pred_lr))

    # Print confusion matrix
    print(confusion_matrix(y_test, y_pred_lr))

    # Predict on the test set
    y_pred_lr = log_reg.predict(X_test)



In [ ]:
# Call the logistic_reg function
logistic_reg(X_test, y_test, X_train, y_train)

Logistic Regression Top Two Predictions:
Test instance 0:
Top predicted class: 0
Probability: 0.9984682253514727

Test instance 1:
Top predicted class: 2
Probability: 0.6382951253797394

Test instance 2:
Top predicted class: 0
Probability: 0.5496795690801204

Test instance 3:
Top predicted class: 0
Probability: 0.9992534481028388

Test instance 4:
Top predicted class: 0
Probability: 0.31977227215945364

Test instance 5:
Top predicted class: 0
Probability: 0.983653951568797

Test instance 6:
Top predicted class: 4
Probability: 0.5091333939094145

Test instance 7:
Top predicted class: 0
Probability: 0.7777735598127686

Test instance 8:
Top predicted class: 0
Probability: 0.9994191666773558

Test instance 9:
Top predicted class: 0
Probability: 0.9919989510572317

Test instance 10:
Top predicted class: 0
Probability: 0.9577303477281774

Test instance 11:
Top predicted class: 0
Probability: 0.9997117147051086

Test instance 12:
Top predicted class: 0
Probability: 0.9979706951565144

Test in

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:

### Decision Tree Classifier
#importing library from sklearn
from sklearn.tree import DecisionTreeClassifier

def d_t_c (X_test, y_test, X_train, y_train):

    DT_clf = DecisionTreeClassifier(random_state=42) #callling and instantiating the built-in DecisionTreeClassifier from Sklearn Scikit
    DT_clf.fit(X_train, y_train)#fit method of the class is called to train the algorithm on the training data, which is passed as parameter to the fit method

    y_pred_dt = DT_clf.predict(X_test)

    # Predict probabilities on the test set
    y_proba_dt = DT_clf.predict_proba(X_test)
    # Get top two predictions
    top_two_predictions_dt = get_top_two_classes(y_proba_dt)

    print("Decision Tree Top Two Predictions:")
    for i in range(len(X_test)):
        print(f"Test instance {i}:")
        top_two = top_two_predictions_dt[i]
        if top_two[0] == -1:  # Both classes are marked
            print(f"Top two predicted classes: {top_two}")
            print(f"Probabilities: {y_proba_dt[i][top_two]}")
        else:
            print(f"Top predicted class: {top_two[0]}")
            print(f"Probability: {y_proba_dt[i][top_two[0]]}")
        print()

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred_dt)
    print(f"Accuracy: {accuracy:.2f}")

    # Print classification report
    print(classification_report(y_test, y_pred_dt))

    # Print confusion matrix
    print(confusion_matrix(y_test, y_pred_dt))

    # Convert the decision tree data back to a DataFrame
    DT_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_dt})

    DT_df.head()


In [ ]:
# Call the Decision Tree Classifier function
d_t_c(X_test, y_test, X_train, y_train)

Decision Tree Top Two Predictions:
Test instance 0:
Top predicted class: 0
Probability: 1.0

Test instance 1:
Top predicted class: 8
Probability: 1.0

Test instance 2:
Top predicted class: 3
Probability: 1.0

Test instance 3:
Top predicted class: 0
Probability: 1.0

Test instance 4:
Top predicted class: 6
Probability: 1.0

Test instance 5:
Top predicted class: 0
Probability: 1.0

Test instance 6:
Top predicted class: 4
Probability: 1.0

Test instance 7:
Top predicted class: 4
Probability: 1.0

Test instance 8:
Top predicted class: 0
Probability: 1.0

Test instance 9:
Top predicted class: 0
Probability: 1.0

Test instance 10:
Top predicted class: 0
Probability: 1.0

Test instance 11:
Top predicted class: 0
Probability: 1.0

Test instance 12:
Top predicted class: 0
Probability: 1.0

Test instance 13:
Top predicted class: 0
Probability: 1.0

Test instance 14:
Top predicted class: 0
Probability: 1.0

Test instance 15:
Top predicted class: 0
Probability: 1.0

Test instance 16:
Top predicted

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [ ]:
###XGBoost
#importing library from xgboost
from xgboost import XGBClassifier

def xgb_model(X_test, y_test, X_train, y_train):
    # Initialize and train the XGBoost classifier
    XGB_clf = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss') #callling and instantiating the built-in XGBoost from XGBoost Classifier
    XGB_clf.fit(X_train, y_train)

    # Predict probabilities on the test set
    y_proba_xgb = XGB_clf.predict_proba(X_test)

    # Get top two predictions
    top_two_predictions_xgb = get_top_two_classes(y_proba_xgb)

    print("XGBoost Top Two Predictions:")
    for i in range(len(X_test)):
        print(f"Test instance {i}:")
        top_two = top_two_predictions_xgb[i]
        if top_two[0] == -1:  # Both classes are marked
            print(f"Top two predicted classes: {top_two}")
            print(f"Probabilities: {y_proba_xgb[i][top_two]}")
        else:
            print(f"Top predicted class: {top_two[0]}")
            print(f"Probability: {y_proba_xgb[i][top_two[0]]}")
        print()
    # Convert the decision tree data back to a DataFrame
    XGB_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_xgb})

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred_xgb)
    print(f"Accuracy: {accuracy:.2f}")

    # Print classification report
    print(classification_report(y_test, y_pred_xgb))

    # Print confusion matrix
    print(confusion_matrix(y_test, y_pred_xgb))

    return y_proba_xgb


In [ ]:
# Call the XGBoost function
xgb_model(X_test, y_test, X_train, y_train)

XGBoost Top Two Predictions:
Test instance 0:
Top predicted class: 0
Probability: 0.9981955885887146

Test instance 1:
Top predicted class: 8
Probability: 0.6861465573310852

Test instance 2:
Top predicted class: 6
Probability: 0.42437440156936646

Test instance 3:
Top predicted class: 0
Probability: 0.9992006421089172

Test instance 4:
Top predicted class: 0
Probability: 0.8562532067298889

Test instance 5:
Top predicted class: 0
Probability: 0.9959537982940674

Test instance 6:
Top predicted class: 4
Probability: 0.9344170689582825

Test instance 7:
Top predicted class: 0
Probability: 0.8873562216758728

Test instance 8:
Top predicted class: 0
Probability: 0.9994654059410095

Test instance 9:
Top predicted class: 0
Probability: 0.9980515241622925

Test instance 10:
Top predicted class: 0
Probability: 0.9492915868759155

Test instance 11:
Top predicted class: 0
Probability: 0.999506950378418

Test instance 12:
Top predicted class: 0
Probability: 0.9949355721473694

Test instance 13:
T

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

array([[9.98195589e-01, 1.74788409e-04, 5.08988160e-04, 2.51583231e-04,
        3.19568790e-04, 1.36335686e-04, 1.36769857e-04, 1.02239923e-04,
        1.74118089e-04],
       [1.09475004e-02, 1.70115717e-02, 5.89126982e-02, 8.67255926e-02,
        1.36431474e-02, 1.12338550e-01, 5.34744328e-03, 8.92693549e-03,
        6.86146557e-01],
       [3.67522269e-01, 4.68316983e-04, 1.30151899e-03, 1.98324516e-01,
        1.40175968e-03, 7.56299356e-04, 4.24374402e-01, 6.30131690e-04,
        5.22078527e-03],
       [9.99200642e-01, 6.21020372e-05, 1.70382027e-05, 2.22412145e-05,
        3.86336469e-04, 3.75926429e-05, 1.87556943e-04, 4.14787355e-05,
        4.50509833e-05],
       [8.56253207e-01, 6.42964756e-03, 1.51075982e-02, 2.69585047e-02,
        5.37875183e-02, 1.30034769e-02, 1.61725823e-02, 7.31435837e-03,
        4.97309957e-03],
       [9.95953798e-01, 1.66866594e-04, 3.48767120e-04, 4.54654044e-04,
        1.99202029e-03, 1.95531975e-04, 5.89097035e-04, 1.68855928e-04,
        1.3

In [ ]:
unique_values = np.unique(y_train)
print(unique_values)


[0 1 2 3 4 5 6 7 8]


In [ ]:

#Neural-Network
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.utils import to_categorical

def nn_model(X_test, y_test, X_train, y_train):

    # Convert labels to categorical
    y_train_categorical = to_categorical(y_train, num_classes=9)
    y_test_categorical = to_categorical(y_test, num_classes=9)

    # Build the neural network model
    model = Sequential()
    model.add(Dense(128, input_dim=X_train.shape[1], activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(9, activation='softmax'))

    # Compile the model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Train the model
    class_weights = {0: 1.0, 1: 1.0, 2: 3.0, 3: 3.0, 4: 3.0, 5: 3.0, 6: 3.0, 7: 3.0, 8: 3.0}
    model.fit(X_train, y_train_categorical, epochs=50, batch_size=32, validation_split=0.2, class_weight=class_weights, callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5)])

    # Predict probabilities on the test set
    y_proba_nn = model.predict(X_test)

    # Get the top two predictions
    top_two_predictions_nn = np.argsort(y_proba_nn, axis=1)[:, -2:][:, ::-1]

    print("Neural Network Top Two Predictions:")
    for i in range(len(X_test)):
        print(f"Test instance {i}:")
        print(f"Top two predicted classes: {top_two_predictions_nn[i]}")
        print(f"Probabilities: {y_proba_nn[i][top_two_predictions_nn[i]]}")

    # Convert probabilities to class predictions
    y_pred_nn = np.argmax(y_proba_nn, axis=1)
    y_test_actual = np.argmax(y_test_categorical, axis=1)

    # Calculate accuracy
    accuracy = accuracy_score(y_test_actual, y_pred_nn)
    print(f"Accuracy: {accuracy:.2f}")

    # Print classification report
    print(classification_report(y_test_actual, y_pred_nn))

    # Print confusion matrix
    print(confusion_matrix(y_test_actual, y_pred_nn))

    return y_proba_nn


In [ ]:
nn_model(X_test, y_test, X_train, y_train)


Epoch 1/50
6/6 [==============================] - 1s 51ms/step - loss: 3.1325 - accuracy: 0.3021 - val_loss: 1.8301 - val_accuracy: 0.6875
Epoch 2/50
6/6 [==============================] - 0s 8ms/step - loss: 2.7771 - accuracy: 0.6406 - val_loss: 1.6304 - val_accuracy: 0.6875
Epoch 3/50
6/6 [==============================] - 0s 9ms/step - loss: 2.5545 - accuracy: 0.6875 - val_loss: 1.4949 - val_accuracy: 0.6875
Epoch 4/50
6/6 [==============================] - 0s 8ms/step - loss: 2.4543 - accuracy: 0.7083 - val_loss: 1.4173 - val_accuracy: 0.6875
Epoch 5/50
6/6 [==============================] - 0s 14ms/step - loss: 2.2813 - accuracy: 0.7188 - val_loss: 1.3481 - val_accuracy: 0.6875
Epoch 6/50
6/6 [==============================] - 0s 8ms/step - loss: 2.2437 - accuracy: 0.7292 - val_loss: 1.3037 - val_accuracy: 0.7708
Epoch 7/50
6/6 [==============================] - 0s 8ms/step - loss: 2.1481 - accuracy: 0.7396 - val_loss: 1.2434 - val_accuracy: 0.7292
Epoch 8/50
6/6 [================

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

array([[9.99744773e-01, 1.09399152e-05, 7.45601792e-05, 1.06217954e-06,
        8.90589072e-05, 2.64402416e-07, 3.81368341e-06, 1.56668939e-05,
        5.99586274e-05],
       [2.21554823e-02, 6.96761860e-03, 2.84688085e-01, 1.06441202e-02,
        1.68575317e-01, 3.58745232e-02, 3.78198514e-04, 9.96788265e-04,
        4.69719917e-01],
       [5.81225574e-01, 1.19486800e-03, 2.73724576e-03, 9.24715120e-03,
        1.11673981e-01, 3.97608289e-03, 2.82617897e-01, 2.15707463e-03,
        5.16999327e-03],
       [9.99468684e-01, 4.49254776e-06, 1.68046045e-05, 6.34754315e-06,
        2.25304611e-04, 2.40712893e-06, 1.50828346e-04, 6.70891750e-05,
        5.81847889e-05],
       [1.13185912e-01, 4.20647021e-03, 5.25042647e-03, 3.95148918e-02,
        3.29769075e-01, 3.16104665e-02, 4.63596076e-01, 2.74336222e-03,
        1.01232668e-02],
       [9.66419876e-01, 1.71572343e-03, 7.62485201e-03, 8.45041999e-04,
        1.49747636e-02, 5.73122641e-04, 3.26843490e-03, 1.33368094e-03,
        3.2

In [ ]:
#Meta-Model
def meta_model(X_test, y_test, X_train, y_train):
    y_proba_nn = nn_model(X_test, y_test, X_train, y_train)
    y_proba_xgb = xgb_model(X_test, y_test, X_train, y_train)

    # Combine the predictions into meta_features
    meta_features = np.hstack((y_proba_nn, y_proba_xgb))

    # Convert y_test back to original label format
    #y_test_labels = np.argmax(y_test, axis=1)

    # Train a meta-model (Logistic Regression)
    meta_model = LogisticRegression(max_iter=1000, random_state=42)
    meta_model.fit(meta_features, y_test)

    # Predict with meta-model on test set
    final_predictions = meta_model.predict(meta_features)

    # Calculate accuracy
    accuracy_meta = accuracy_score(y_test, final_predictions)
    print(f"Meta-Model Accuracy: {accuracy_meta:.2f}")

    # Print classification report
    print(classification_report(y_test, final_predictions))

    # Print confusion matrix
    print(confusion_matrix(y_test, final_predictions))

    for i, prediction in enumerate(final_predictions):
        print(f"Test instance {i}: Predicted class: {prediction}")

In [ ]:
#Meta model
meta_model(X_test, y_test, X_train, y_train)

Epoch 1/50
6/6 [==============================] - 2s 63ms/step - loss: 3.3518 - accuracy: 0.2083 - val_loss: 2.0252 - val_accuracy: 0.6250
Epoch 2/50
6/6 [==============================] - 0s 15ms/step - loss: 2.9827 - accuracy: 0.5781 - val_loss: 1.7762 - val_accuracy: 0.6875
Epoch 3/50
6/6 [==============================] - 0s 13ms/step - loss: 2.6672 - accuracy: 0.6927 - val_loss: 1.5603 - val_accuracy: 0.6875
Epoch 4/50
6/6 [==============================] - 0s 14ms/step - loss: 2.5935 - accuracy: 0.6927 - val_loss: 1.4049 - val_accuracy: 0.6875
Epoch 5/50
6/6 [==============================] - 0s 15ms/step - loss: 2.5122 - accuracy: 0.6979 - val_loss: 1.3324 - val_accuracy: 0.6875
Epoch 6/50
6/6 [==============================] - 0s 14ms/step - loss: 2.3702 - accuracy: 0.7083 - val_loss: 1.3113 - val_accuracy: 0.7500
Epoch 7/50
6/6 [==============================] - 0s 12ms/step - loss: 2.2046 - accuracy: 0.6979 - val_loss: 1.3003 - val_accuracy: 0.7500
Epoch 8/50
6/6 [===========

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

XGBoost Top Two Predictions:
Test instance 0:
Top predicted class: 0
Probability: 0.9981955885887146

Test instance 1:
Top predicted class: 8
Probability: 0.6861465573310852

Test instance 2:
Top predicted class: 6
Probability: 0.42437440156936646

Test instance 3:
Top predicted class: 0
Probability: 0.9992006421089172

Test instance 4:
Top predicted class: 0
Probability: 0.8562532067298889

Test instance 5:
Top predicted class: 0
Probability: 0.9959537982940674

Test instance 6:
Top predicted class: 4
Probability: 0.9344170689582825

Test instance 7:
Top predicted class: 0
Probability: 0.8873562216758728

Test instance 8:
Top predicted class: 0
Probability: 0.9994654059410095

Test instance 9:
Top predicted class: 0
Probability: 0.9980515241622925

Test instance 10:
Top predicted class: 0
Probability: 0.9492915868759155

Test instance 11:
Top predicted class: 0
Probability: 0.999506950378418

Test instance 12:
Top predicted class: 0
Probability: 0.9949355721473694

Test instance 13:
T

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [ ]:
# Load the new data into a pandas DataFrame
new_data = pd.read_excel(dataset_path_surveys)

In [ ]:
def replace_test_data(X_test, y_test, new_data):

    # Define features and target variable
    new_X_test = new_data.drop(['prediction','TempId'], axis = 1) # Drop TempId as it is not a feature
    new_y_test = new_data['prediction']

    #z-score new data - calling function
    new_X_scaled_df, new_y_test = normalization (new_X_test, new_y_test)

    # Convert the scaled data back to a DataFrame
    #new_y_test_df = pd.DataFrame(new_y_test)

    # Display the first few rows of the scaled DataFrame
    print("Z-Scored Variables (X): ", + new_X_scaled_df.head())
    print(new_X_scaled_df.shape)

    print("\n Target Variable (y):\n", + new_y_test)

      # Convert X_test and y_test to DataFrames if they are not already
    if not isinstance(X_test, pd.DataFrame):
        X_test = pd.DataFrame(X_test)
    #if not isinstance(y_test, pd.DataFrame):
     #   y_test = pd.DataFrame(y_test)


    # Drop existing data from X_test and y_test
    #X_test.drop(X_test.index, inplace=True)
    #y_test.drop(y_test.index, inplace=True)

    # Add new data to X_test and y_test
    X_test = pd.concat([X_test, new_X_scaled_df], ignore_index=True)
    y_test = pd.concat([y_test, new_y_test], ignore_index=True)

    return X_test, y_test


In [ ]:

X_test, y_test = replace_test_data(X_test, y_test, new_data)


Z-Scored Variables (X):          Age  Working Age  Credit Score    Income  Client Payment  \
0  2.657994    -0.420500     -1.481684 -0.061503        0.497785   
1 -1.054900    -0.515274     -0.311633 -0.300798       -0.278157   
2 -1.054900    -0.799595      0.150426 -1.482732        0.676849   
3 -1.054900    -0.610047     -0.617187  0.511202        2.228734   
4 -1.124955    -0.894368     -0.035888  1.267763        1.691543   

   House Price (Casa Popular)  Profesionist  Residence  Employment Type  \
0                   -0.265939     -2.422120   0.396615         2.432546   
1                    0.490952      0.412861  -2.521338         0.958709   
2                    0.888937      0.412861  -2.521338         2.432546   
3                   -1.210843      0.412861  -2.521338         0.958709   
4                   -0.509692     -2.422120  -2.521338         2.432546   

   Dependents  
0    1.009756  
1   -0.990338  
2   -0.990338  
3   -0.990338  
4   -0.990338  
(103, 10)

 Target 

In [ ]:

#Ensuring correct data size
print('x_train: ', X_train.shape)
print('y_train: ',y_train.shape)
print('x_test: ', X_test.shape)
print('y_test: ', y_test.shape)

x_train:  (240, 10)
y_train:  (240,)
x_test:  (163, 10)
y_test:  (163,)


In [ ]:
print('######LOGISTIC REGRESSION MODEL#####')
# Call the logistic_reg function
logistic_reg(X_test, y_test, X_train, y_train)

print('######Decision Tree Classifier#####')
# Call the Decision Tree Classifier function
d_t_c(X_test, y_test, X_train, y_train)


print('#####XGBoost Model#####')
# Call the XGBoost function
xgb_model(X_test, y_test, X_train, y_train)

print('#####NN Model#####')
nn_model(X_test, y_test, X_train, y_train)

print('#####Meta Model#####')
meta_model(X_test, y_test, X_train, y_train)


######LOGISTIC REGRESSION MODEL#####
Logistic Regression Top Two Predictions:
Test instance 0:
Top predicted class: 0
Probability: 0.9984682253514727

Test instance 1:
Top predicted class: 2
Probability: 0.6382951253797394

Test instance 2:
Top predicted class: 0
Probability: 0.5496795690801204

Test instance 3:
Top predicted class: 0
Probability: 0.9992534481028388

Test instance 4:
Top predicted class: 0
Probability: 0.31977227215945364

Test instance 5:
Top predicted class: 0
Probability: 0.983653951568797

Test instance 6:
Top predicted class: 4
Probability: 0.5091333939094145

Test instance 7:
Top predicted class: 0
Probability: 0.7777735598127686

Test instance 8:
Top predicted class: 0
Probability: 0.9994191666773558

Test instance 9:
Top predicted class: 0
Probability: 0.9919989510572317

Test instance 10:
Top predicted class: 0
Probability: 0.9577303477281774

Test instance 11:
Top predicted class: 0
Probability: 0.9997117147051086

Test instance 12:
Top predicted class: 0
Pro

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.61      0.96      0.74        93
           1       0.00      0.00      0.00         5
           2       0.50      1.00      0.67         1
           4       0.40      0.25      0.31         8
           5       0.00      0.00      0.00         1
           6       0.56      0.09      0.16        54
           7       0.00      0.00      0.00         1

    accuracy                           0.60       163
   macro avg       0.30      0.33      0.27       163
weighted avg       0.55      0.60      0.50       163

[[89  0  0  0  1  3  0]
 [ 4  0  1  0  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 5  0  0  2  0  1  0]
 [ 1  0  0  0  0  0  0]
 [46  0  0  3  0  5  0]
 [ 1  0  0  0  0  0  0]]
######Decision Tree Classifier#####
Decision Tree Top Two Predictions:
Test instance 0:
Top predicted class: 0
Probability: 1.0

Test instance 1:
Top predicted class: 8
Probability: 1.0

Test instance 2:
Top predicted class: 3
Probabi

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

              precision    recall  f1-score   support

           0       0.67      0.75      0.71        93
           1       0.00      0.00      0.00         5
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         0
           4       0.11      0.50      0.18         8
           5       0.00      0.00      0.00         1
           6       0.67      0.11      0.19        54
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         0

    accuracy                           0.49       163
   macro avg       0.16      0.15      0.12       163
weighted avg       0.61      0.49      0.48       163

[[70  0  0  4 13  2  3  0  1]
 [ 3  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0]
 [ 4  0  0  0  4  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0]
 [27  0  0  1 19  1  6  0  0]
 [ 0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]
#####XGBoost Model#####


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

6/6 [==============================] - 1s 43ms/step - loss: 3.0851 - accuracy: 0.5677 - val_loss: 1.7337 - val_accuracy: 0.6875
Epoch 2/50
6/6 [==============================] - 0s 8ms/step - loss: 2.8383 - accuracy: 0.6927 - val_loss: 1.4768 - val_accuracy: 0.6875
Epoch 3/50
6/6 [==============================] - 0s 14ms/step - loss: 2.7152 - accuracy: 0.6979 - val_loss: 1.3591 - val_accuracy: 0.6875
Epoch 4/50
6/6 [==============================] - 0s 12ms/step - loss: 2.5030 - accuracy: 0.7031 - val_loss: 1.2895 - val_accuracy: 0.6875
Epoch 5/50
6/6 [==============================] - 0s 13ms/step - loss: 2.3965 - accuracy: 0.7031 - val_loss: 1.2566 - val_accuracy: 0.6875
Epoch 6/50
6/6 [==============================] - 0s 15ms/step - loss: 2.1897 - accuracy: 0.7135 - val_loss: 1.2248 - val_accuracy: 0.7083
Epoch 7/50
6/6 [==============================] - 0s 14ms/step - loss: 2.2534 - accuracy: 0.7135 - val_loss: 1.2033 - val_accuracy: 0.7500
Epoch 8/50
6/6 [=======================

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

6/6 [==============================] - 1s 46ms/step - loss: 3.4147 - accuracy: 0.1250 - val_loss: 1.9701 - val_accuracy: 0.6042
Epoch 2/50
6/6 [==============================] - 0s 12ms/step - loss: 2.9428 - accuracy: 0.5156 - val_loss: 1.6986 - val_accuracy: 0.6875
Epoch 3/50
6/6 [==============================] - 0s 8ms/step - loss: 2.8057 - accuracy: 0.6562 - val_loss: 1.5115 - val_accuracy: 0.6875
Epoch 4/50
6/6 [==============================] - 0s 12ms/step - loss: 2.5248 - accuracy: 0.7135 - val_loss: 1.3873 - val_accuracy: 0.6875
Epoch 5/50
6/6 [==============================] - 0s 11ms/step - loss: 2.4454 - accuracy: 0.6979 - val_loss: 1.3251 - val_accuracy: 0.6875
Epoch 6/50
6/6 [==============================] - 0s 9ms/step - loss: 2.3074 - accuracy: 0.7031 - val_loss: 1.2735 - val_accuracy: 0.6875
Epoch 7/50
6/6 [==============================] - 0s 8ms/step - loss: 2.2998 - accuracy: 0.6927 - val_loss: 1.2258 - val_accuracy: 0.6875
Epoch 8/50
6/6 [=========================

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.


Test instance 129:
Top predicted class: 0
Probability: 0.9930834770202637

Test instance 130:
Top predicted class: 0
Probability: 0.9772439002990723

Test instance 131:
Top predicted class: 0
Probability: 0.9987105131149292

Test instance 132:
Top predicted class: 0
Probability: 0.9979548454284668

Test instance 133:
Top predicted class: 0
Probability: 0.9971099495887756

Test instance 134:
Top predicted class: 0
Probability: 0.9851749539375305

Test instance 135:
Top predicted class: 0
Probability: 0.994949221611023

Test instance 136:
Top predicted class: 0
Probability: 0.9968133568763733

Test instance 137:
Top predicted class: 0
Probability: 0.9950317144393921

Test instance 138:
Top predicted class: 0
Probability: 0.9961773157119751

Test instance 139:
Top predicted class: 0
Probability: 0.9580032825469971

Test instance 140:
Top predicted class: 0
Probability: 0.9965829253196716

Test instance 141:
Top predicted class: 0
Probability: 0.9903807044029236

Test instance 142:
Top pr

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [ ]:
# Get the top two predictions
top_two_predictions_xgb = np.argsort(y_proba_xgb, axis=1)[:, -2:][:, ::-1]
#print("Top Predictions:", top_two_predictions_xgb,"")

for i in range(len(X_test)):
        print(f"ID: {i}")
        print(f"Top two predicted classes: {top_two_predictions_xgb[i]}")
        print(f"Probabilities: {y_proba_xgb[i][top_two_predictions_xgb[i]]}")